export const images = {
  grifinoria: require("./grifinoria.jpg"),
  corvinal: require("./corvinal.jpg"),
  lufalufa: require("./lufa-lufa.jpg"),
  sonserina: require("./sonserina.jpg"),
  harryPorco: require("./harry-potter.jpg"),
  hermi: require("./hermione.jpg"),
  ronyy: require("./rony.jpg"),
  backG: require("./back-g.jpg"),
  hogwarts: require("./hogwarts.gif"),
  luna: require ("./luna.jpg"),
  cho: require ("./chang.jpg"),
  backC: require ("./back-c.jpg"),
  Cedric: require ("./cedric.png"),
  Tonks: require ("./ninfadora.jpg"),
  backL: require ("./back-l.jpg"),
  backS: require ("./back-s.jpg"),
  lord: require ("./voldemort.png"),
  snape: require ("./snape.jpg"),
  draco: require ("./draco.jpg")
}